version: "3.1"
services:
  ers-app:
    container_name: ers-app
    image: vulka9n/ersservice:latest
    restart: on-failure
    ports:
      - 10500:8080
    environment:
      WAIT_HOSTS: mysql:3306
    depends_on:
      - docker-mysql

  docker-mysql:
    container_name: docker-mysql
    image: mysql
    restart: always
    ports:
      - "6666:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_ROOT_HOST: "%"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    healthcheck:
      test: '/user/bin/mysql --user=root --password=1234 --execute \"SHOW DATABASES \"'
      interval: 4s
      timeout: 20s
      retries: 5
