FROM adoptopenjdk/openjdk11:latest
ADD build/libs/expensereimbursementsystem-0.0.1-SNAPSHOT.jar expensereimbursementsystem-0.0.1-SNAPSHOT.jar
ENTRYPOINT [ "java","-jar","expensereimbursementsystem-0.0.1-SNAPSHOT.jar" ]
